### ISSUE TITLE
 user-can-search-for-an-ingredient

### ISSUE THREAD

**Issue by Jc-Leon** [Jc-Leon/Drinks4U#1]
## 🖼️ Wireframes
<img width="1157" alt="Screen Shot 2021-09-21 at 3 14 06 PM" src="https://user-images.githubusercontent.com/84432043/134254902-edf4b108-f4c9-4077-9e63-bd2ea7754a35.png">
<img width="286" alt="Screen Shot 2021-09-21 at 3 22 51 PM" src="https://user-images.githubusercontent.com/84432043/134255651-36db9e04-0402-40f6-8eb3-c1cdd09f8198.png">

## ✅ Task List

- [x] Set Video Background
- [x] Create search bar at center of document for user to search alcohol upon enter key
- [x] Create a search button alongside search bar to give user the option to click rather than enter
- [x] Add listener on enter of search bar and button to fire GET request
- [x] Add placeholder of "What are we drinking today?" inside the search bar
- [x] Create transparent bar to the top of the document 
- [x] Place Logo on top left of document on top of transparent bar resize accordingly
- [x] Place Favorites Logo on Right on top of transparent bar resize accordingly
- [x] Move searchbar to top of document upon search 
- [x] Clean up unused CSS
- [x] Make sure page is mobile responsive
- [x] Ensure functionally 
- [x] On to next feature 😀
