### ISSUE TITLE
user-can-view-all-drinks-with-that-ingredient

### ISSUE THREAD

**Issue by Jc-Leon** [Jc-Leon/Drinks4U#2]
## 🖼️ Wireframes

![Screen Shot 2021-09-22 at 11 19 44 AM](https://user-images.githubusercontent.com/84432043/134399858-3f35b701-aa8c-451f-bd98-3fb30f11c853.png)
![Screen Shot 2021-09-22 at 11 20 03 AM](https://user-images.githubusercontent.com/84432043/134399874-e480b8cc-a471-404c-a517-c89ef427c3d5.png)

## ✅ Task List

- [x] Fix search bar to top of page
- [x] Create a flexbox with a transparent background to be able to fit img and text
- [x] With the information from the API append img and name of drink to the flexbox
- [x] Add text "Find out more"
- [x] Round out corners
- [x] Clean up unused CSS
- [x] Make sure page is mobile responsive
- [x] Ensure functionally 
- [x] On to next feature 😀
