### ISSUE TITLE
user-can-view-the-recipe

### ISSUE THREAD

**Issue by Jc-Leon** [Jc-Leon/Drinks4U#3]
## 🖼️ Wireframes
![Screen Shot 2021-09-23 at 5 45 50 PM](https://user-images.githubusercontent.com/84432043/134601761-d2034b9f-757b-41c7-81a8-a0e36e3daeed.png)
![Screen Shot 2021-09-23 at 5 45 35 PM](https://user-images.githubusercontent.com/84432043/134601763-caab01e5-6a23-4a8e-b684-6a06422e7f88.png)
## ✅ Task List

- [x] Upon click on which parent nearest clicked, display full cocktail ingredients
- [x] Swap to new view to contain full cocktail ingredients
- [x] Create layout using flex box
- [x] Append API information onto documentt
- [x] Clean up unused CSS
- [x] Make sure page is mobile responsive
- [x] Ensure functionally 
- [x] On to next feature 😀
